# Generated by Django 6.0.6 on 2026-06-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedresume',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='extracted_certifications',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='extracted_education',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
