# Generated by Django 6.0.6 on 2026-06-18 18:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_parsedresume_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comparison_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_new', to='resumes.resume')),
                ('resume_old', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_old', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_comparisons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
