# Generated by Django 6.0.6 on 2026-06-20 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_resumecomparison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumecomparison',
            name='comparison_data',
        ),
        migrations.RemoveField(
            model_name='resumecomparison',
            name='resume_new',
        ),
        migrations.RemoveField(
            model_name='resumecomparison',
            name='resume_old',
        ),
        migrations.AddField(
            model_name='resumecomparison',
            name='added_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumecomparison',
            name='added_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumecomparison',
            name='after_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_after', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumecomparison',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumecomparison',
            name='ats_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumecomparison',
            name='before_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_before', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumecomparison',
            name='health_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumecomparison',
            name='recruiter_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumecomparison',
            name='removed_keywords',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumecomparison',
            name='removed_skills',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='ResumeAnalysisSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ats_score', models.IntegerField(default=0)),
                ('recruiter_score', models.IntegerField(default=0)),
                ('health_score', models.IntegerField(default=0)),
                ('missing_skills', models.JSONField(default=list)),
                ('missing_keywords', models.JSONField(default=list)),
                ('improvement_suggestions', models.JSONField(default=list)),
                ('extracted_skills', models.JSONField(default=list)),
                ('extracted_projects', models.JSONField(default=list)),
                ('extracted_experience', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_snapshot', to='resumes.resume')),
            ],
        ),
    ]
