# Generated by Django 6.0.6 on 2026-06-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_remove_resumecomparison_comparison_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedresume',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
