# Generated by Django 6.0.6 on 2026-07-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_parsedresume_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedresume',
            name='professional_summary',
            field=models.TextField(blank=True),
        ),
    ]
