# Generated by Django 6.0.7 on 2026-08-02 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_parsedresume_professional_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumecomparison',
            name='after_resume',
        ),
        migrations.RemoveField(
            model_name='resumecomparison',
            name='before_resume',
        ),
        migrations.RemoveField(
            model_name='resumecomparison',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='parsedresume',
            name='professional_summary',
        ),
        migrations.AddField(
            model_name='resume',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Microsoft Word Document')], default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='resume',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resume',
            name='raw_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='parsedresume',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(choices=[('SUMMARY', 'Professional Summary'), ('EXPERIENCE', 'Work Experience'), ('EDUCATION', 'Education'), ('SKILLS', 'Skills'), ('PROJECTS', 'Projects'), ('CERTIFICATIONS', 'Certifications'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('content', models.TextField()),
                ('ordinal_position', models.PositiveIntegerField(default=1)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='resumes.resume')),
            ],
            options={
                'ordering': ['ordinal_position'],
            },
        ),
        migrations.DeleteModel(
            name='ResumeAnalysisSnapshot',
        ),
        migrations.DeleteModel(
            name='ResumeComparison',
        ),
    ]
