# Generated by Django 6.0.7 on 2026-08-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_reset_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
