# Generated by Django 6.0.6 on 2026-06-20 19:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='job',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='user',
        ),
        migrations.CreateModel(
            name='SelectedJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_job_id', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('apply_link', models.URLField(max_length=1000)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('SAVED', 'Saved'), ('NOT_APPLIED', 'Not Applied'), ('APPLIED', 'Applied'), ('INTERVIEW_CALL_RECEIVED', 'Interview Call Received'), ('REJECTED', 'Rejected'), ('OFFER_RECEIVED', 'Offer Received')], default='SAVED', max_length=50)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_by_users', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='SavedJob',
        ),
    ]
