# Generated by Django 6.0.6 on 2026-06-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atsanalysis',
            name='readability_score',
        ),
        migrations.AddField(
            model_name='atsanalysis',
            name='completeness_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atsanalysis',
            name='education_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atsanalysis',
            name='experience_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='atsanalysis',
            name='skills_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='atsanalysis',
            name='ats_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='atsanalysis',
            name='formatting_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='atsanalysis',
            name='keyword_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
