# Generated by Django 6.0.6 on 2026-06-18 18:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_remove_atsanalysis_readability_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewpreparation',
            name='difficulty_level',
            field=models.CharField(default='intermediate', max_length=50),
        ),
        migrations.CreateModel(
            name='CareerReadinessSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('career_score', models.IntegerField()),
                ('factors', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
