# Generated by Django 6.0.6 on 2026-06-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_interviewpreparation_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgapanalysis',
            name='roadmap',
            field=models.JSONField(default=list),
        ),
    ]
