# Generated by Django 6.0.6 on 2026-07-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_skillgapanalysis_roadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeimprovement',
            name='tailored_content',
            field=models.TextField(blank=True),
        ),
    ]
