# Generated by Django 6.0.7 on 2026-08-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_resumeimprovement_tailored_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeimprovement',
            name='jd_tailored_content',
            field=models.TextField(blank=True),
        ),
    ]
