# Generated by Django 6.0.6 on 2026-09-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_resumeimprovement_jd_tailored_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeimprovement',
            name='markdown_baseline',
            field=models.TextField(blank=True),
        ),
    ]
